columns<-c("character", "character", "numeric", "numeric", "numeric", "numeric","numeric", "numeric", "numeric")
hhpc = read.table("household_power_consumption.txt", sep=";", header = TRUE,colClasses = columns, na.strings = "?")
#head(hhpc)
hhpc$Date_Time = strptime(paste(hhpc$Date, hhpc$Time),format="%d/%m/%Y %H:%M:%S")
hhpc <- subset(hhpc,as.Date(Date_Time) >= as.Date("2007-02-01") & as.Date(Date_Time) <= as.Date("2007-02-02"))

png("plot4.png", height=480, width=480)
par(mfrow=c(2,2))
plot(hhpc$Date_Time, hhpc$Global_active_power, pch=NA, xlab="", ylab="Global Active Power (kilowatts)") 
lines(hhpc$Date_Time, hhpc$Global_active_power)
plot(hhpc$Date_Time, hhpc$Voltage, ylab="Voltage", xlab="datetime", pch=NA) 
lines(hhpc$Date_Time, hhpc$Voltage)
plot(hhpc$Date_Time,hhpc$Sub_metering_1, pch=NA,xlab="", ylab="Energy sub metering") 
lines(hhpc$Date_Time, hhpc$Sub_metering_1) 
lines(hhpc$Date_Time, hhpc$Sub_metering_2, col='red') 
lines(hhpc$Date_Time, hhpc$Sub_metering_3, col='blue') 
legend('topright', c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty = c(1,1,1),col = c('black', 'red', 'blue'), bty = 'n')
with(hhpc, plot(Date_Time, Global_reactive_power, xlab='datetime', pch=NA)) 
with(hhpc, lines(Date_Time, Global_reactive_power))
dev.off() 